name: AWS ML CI/CD Pipeline
on:
  push:
    branches: [main]  # Trigger on every push to main
jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run ML Training and Deployment
        run: |
          pip install sagemaker boto3
          python RAG_LLM_WC_Code.py # This 'll run your colab code in AWS
